FROM golang:1.25 as builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o backend .


FROM golang:1.25
WORKDIR /app
COPY --from=builder /app/backend /app/backend
EXPOSE 5050
ENV MONGO_URI=mongodb+srv://varis:Ryu2005xD@resproj.qwizgqr.mongodb.net/?retryWrites=true&w=majority&appName=resProj
ENV PORT=5050
ENV DATABASE=bitKai
CMD [ "/app/backend" ]
