FROM golang:1.25 as builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o backend .


FROM golang:1.25
WORKDIR /app
COPY --from=builder /app/backend /app/backend
EXPOSE 5050
CMD [ "/app/backend" ]
